// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zad3.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_zad3_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_zad3_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_zad3_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_zad3_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_zad3_2eproto;
class Company;
struct CompanyDefaultTypeInternal;
extern CompanyDefaultTypeInternal _Company_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::Company* Arena::CreateMaybeMessage<::Company>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class Company final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Company) */ {
 public:
  inline Company() : Company(nullptr) {}
  ~Company() override;
  explicit PROTOBUF_CONSTEXPR Company(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Company(const Company& from);
  Company(Company&& from) noexcept
    : Company() {
    *this = ::std::move(from);
  }

  inline Company& operator=(const Company& from) {
    CopyFrom(from);
    return *this;
  }
  inline Company& operator=(Company&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Company& default_instance() {
    return *internal_default_instance();
  }
  static inline const Company* internal_default_instance() {
    return reinterpret_cast<const Company*>(
               &_Company_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Company& a, Company& b) {
    a.Swap(&b);
  }
  inline void Swap(Company* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Company* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Company* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Company>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Company& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Company& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Company* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Company";
  }
  protected:
  explicit Company(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLegalAddressFieldNumber = 2,
    kCompanyNameFieldNumber = 3,
    kTypeActivityFieldNumber = 4,
    kYearCreatFieldNumber = 1,
    kForeignEconomicActivityFieldNumber = 5,
  };
  // required string legalAddress = 2;
  bool has_legaladdress() const;
  private:
  bool _internal_has_legaladdress() const;
  public:
  void clear_legaladdress();
  const std::string& legaladdress() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_legaladdress(ArgT0&& arg0, ArgT... args);
  std::string* mutable_legaladdress();
  PROTOBUF_NODISCARD std::string* release_legaladdress();
  void set_allocated_legaladdress(std::string* legaladdress);
  private:
  const std::string& _internal_legaladdress() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_legaladdress(const std::string& value);
  std::string* _internal_mutable_legaladdress();
  public:

  // required string companyName = 3;
  bool has_companyname() const;
  private:
  bool _internal_has_companyname() const;
  public:
  void clear_companyname();
  const std::string& companyname() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_companyname(ArgT0&& arg0, ArgT... args);
  std::string* mutable_companyname();
  PROTOBUF_NODISCARD std::string* release_companyname();
  void set_allocated_companyname(std::string* companyname);
  private:
  const std::string& _internal_companyname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_companyname(const std::string& value);
  std::string* _internal_mutable_companyname();
  public:

  // optional string typeActivity = 4;
  bool has_typeactivity() const;
  private:
  bool _internal_has_typeactivity() const;
  public:
  void clear_typeactivity();
  const std::string& typeactivity() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_typeactivity(ArgT0&& arg0, ArgT... args);
  std::string* mutable_typeactivity();
  PROTOBUF_NODISCARD std::string* release_typeactivity();
  void set_allocated_typeactivity(std::string* typeactivity);
  private:
  const std::string& _internal_typeactivity() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_typeactivity(const std::string& value);
  std::string* _internal_mutable_typeactivity();
  public:

  // required int32 yearCreat = 1;
  bool has_yearcreat() const;
  private:
  bool _internal_has_yearcreat() const;
  public:
  void clear_yearcreat();
  int32_t yearcreat() const;
  void set_yearcreat(int32_t value);
  private:
  int32_t _internal_yearcreat() const;
  void _internal_set_yearcreat(int32_t value);
  public:

  // optional bool foreignEconomicActivity = 5;
  bool has_foreigneconomicactivity() const;
  private:
  bool _internal_has_foreigneconomicactivity() const;
  public:
  void clear_foreigneconomicactivity();
  bool foreigneconomicactivity() const;
  void set_foreigneconomicactivity(bool value);
  private:
  bool _internal_foreigneconomicactivity() const;
  void _internal_set_foreigneconomicactivity(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Company)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr legaladdress_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr companyname_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr typeactivity_;
  int32_t yearcreat_;
  bool foreigneconomicactivity_;
  friend struct ::TableStruct_zad3_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Company

// required int32 yearCreat = 1;
inline bool Company::_internal_has_yearcreat() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool Company::has_yearcreat() const {
  return _internal_has_yearcreat();
}
inline void Company::clear_yearcreat() {
  yearcreat_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline int32_t Company::_internal_yearcreat() const {
  return yearcreat_;
}
inline int32_t Company::yearcreat() const {
  // @@protoc_insertion_point(field_get:Company.yearCreat)
  return _internal_yearcreat();
}
inline void Company::_internal_set_yearcreat(int32_t value) {
  _has_bits_[0] |= 0x00000008u;
  yearcreat_ = value;
}
inline void Company::set_yearcreat(int32_t value) {
  _internal_set_yearcreat(value);
  // @@protoc_insertion_point(field_set:Company.yearCreat)
}

// required string legalAddress = 2;
inline bool Company::_internal_has_legaladdress() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Company::has_legaladdress() const {
  return _internal_has_legaladdress();
}
inline void Company::clear_legaladdress() {
  legaladdress_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Company::legaladdress() const {
  // @@protoc_insertion_point(field_get:Company.legalAddress)
  return _internal_legaladdress();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Company::set_legaladdress(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 legaladdress_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Company.legalAddress)
}
inline std::string* Company::mutable_legaladdress() {
  std::string* _s = _internal_mutable_legaladdress();
  // @@protoc_insertion_point(field_mutable:Company.legalAddress)
  return _s;
}
inline const std::string& Company::_internal_legaladdress() const {
  return legaladdress_.Get();
}
inline void Company::_internal_set_legaladdress(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  legaladdress_.Set(value, GetArenaForAllocation());
}
inline std::string* Company::_internal_mutable_legaladdress() {
  _has_bits_[0] |= 0x00000001u;
  return legaladdress_.Mutable(GetArenaForAllocation());
}
inline std::string* Company::release_legaladdress() {
  // @@protoc_insertion_point(field_release:Company.legalAddress)
  if (!_internal_has_legaladdress()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  auto* p = legaladdress_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (legaladdress_.IsDefault()) {
    legaladdress_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Company::set_allocated_legaladdress(std::string* legaladdress) {
  if (legaladdress != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  legaladdress_.SetAllocated(legaladdress, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (legaladdress_.IsDefault()) {
    legaladdress_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Company.legalAddress)
}

// required string companyName = 3;
inline bool Company::_internal_has_companyname() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Company::has_companyname() const {
  return _internal_has_companyname();
}
inline void Company::clear_companyname() {
  companyname_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& Company::companyname() const {
  // @@protoc_insertion_point(field_get:Company.companyName)
  return _internal_companyname();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Company::set_companyname(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000002u;
 companyname_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Company.companyName)
}
inline std::string* Company::mutable_companyname() {
  std::string* _s = _internal_mutable_companyname();
  // @@protoc_insertion_point(field_mutable:Company.companyName)
  return _s;
}
inline const std::string& Company::_internal_companyname() const {
  return companyname_.Get();
}
inline void Company::_internal_set_companyname(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  companyname_.Set(value, GetArenaForAllocation());
}
inline std::string* Company::_internal_mutable_companyname() {
  _has_bits_[0] |= 0x00000002u;
  return companyname_.Mutable(GetArenaForAllocation());
}
inline std::string* Company::release_companyname() {
  // @@protoc_insertion_point(field_release:Company.companyName)
  if (!_internal_has_companyname()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  auto* p = companyname_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (companyname_.IsDefault()) {
    companyname_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Company::set_allocated_companyname(std::string* companyname) {
  if (companyname != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  companyname_.SetAllocated(companyname, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (companyname_.IsDefault()) {
    companyname_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Company.companyName)
}

// optional string typeActivity = 4;
inline bool Company::_internal_has_typeactivity() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Company::has_typeactivity() const {
  return _internal_has_typeactivity();
}
inline void Company::clear_typeactivity() {
  typeactivity_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000004u;
}
inline const std::string& Company::typeactivity() const {
  // @@protoc_insertion_point(field_get:Company.typeActivity)
  return _internal_typeactivity();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Company::set_typeactivity(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000004u;
 typeactivity_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Company.typeActivity)
}
inline std::string* Company::mutable_typeactivity() {
  std::string* _s = _internal_mutable_typeactivity();
  // @@protoc_insertion_point(field_mutable:Company.typeActivity)
  return _s;
}
inline const std::string& Company::_internal_typeactivity() const {
  return typeactivity_.Get();
}
inline void Company::_internal_set_typeactivity(const std::string& value) {
  _has_bits_[0] |= 0x00000004u;
  typeactivity_.Set(value, GetArenaForAllocation());
}
inline std::string* Company::_internal_mutable_typeactivity() {
  _has_bits_[0] |= 0x00000004u;
  return typeactivity_.Mutable(GetArenaForAllocation());
}
inline std::string* Company::release_typeactivity() {
  // @@protoc_insertion_point(field_release:Company.typeActivity)
  if (!_internal_has_typeactivity()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000004u;
  auto* p = typeactivity_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (typeactivity_.IsDefault()) {
    typeactivity_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Company::set_allocated_typeactivity(std::string* typeactivity) {
  if (typeactivity != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  typeactivity_.SetAllocated(typeactivity, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (typeactivity_.IsDefault()) {
    typeactivity_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Company.typeActivity)
}

// optional bool foreignEconomicActivity = 5;
inline bool Company::_internal_has_foreigneconomicactivity() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool Company::has_foreigneconomicactivity() const {
  return _internal_has_foreigneconomicactivity();
}
inline void Company::clear_foreigneconomicactivity() {
  foreigneconomicactivity_ = false;
  _has_bits_[0] &= ~0x00000010u;
}
inline bool Company::_internal_foreigneconomicactivity() const {
  return foreigneconomicactivity_;
}
inline bool Company::foreigneconomicactivity() const {
  // @@protoc_insertion_point(field_get:Company.foreignEconomicActivity)
  return _internal_foreigneconomicactivity();
}
inline void Company::_internal_set_foreigneconomicactivity(bool value) {
  _has_bits_[0] |= 0x00000010u;
  foreigneconomicactivity_ = value;
}
inline void Company::set_foreigneconomicactivity(bool value) {
  _internal_set_foreigneconomicactivity(value);
  // @@protoc_insertion_point(field_set:Company.foreignEconomicActivity)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_zad3_2eproto
